

services:
  # React Frontend
  client:
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - server
      - socket
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - mern_network

  # Express Backend API
  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    command: npm run dev         # Use nodemon script
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - mern_network
    restart: unless-stopped

  # Socket.io Chat Service
  socket:
    build: ./socket
    ports:
      - "8000:8000"
    env_file:
      - ./socket/.env
    command: npm run dev         # Use nodemon script
    volumes:
      - ./socket:/app
      - /app/node_modules
    networks:
      - mern_network
    restart: unless-stopped

# Define custom network
networks:
  mern_network:
    driver: bridge
